version: "3.9"

services:
  bot:
    build: .
    container_name: gtd_gpt
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - GUILD_ID=${GUILD_ID}
      - OLLAMA_MODEL=${OLLAMA_MODEL}
    restart: unless-stopped
    volumes:
      - ./characters:/app/characters
      - ./baseSystem.txt:/app/baseSystem.txt
    network_mode: host
