services:
  bot:
    build: .
    container_name: gtd_gpt
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - GUILD_ID=${GUILD_ID}
      - OLLAMA_MODEL=${OLLAMA_MODEL}
    restart: unless-stopped
    network_mode: host
